//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodImmo.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Anomalie : Action
    {
    
        public virtual Documentation AnomalieDeDocumentation { get; set; }
        public virtual VersionDeDocument AnomalieDeVersionDeDocument { get; set; }
        public virtual Contrat AnomalieDeContrat { get; set; }
        public virtual CompteBancaire AnomalieDeCompteBancaire { get; set; }
    }
}
