//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodImmo.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Lot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lot()
        {
            this.Commentaires = new HashSet<Commentaire>();
            this.ClesDeRepartition = new HashSet<CleDeRepartition>();
        }
    
        public long Id { get; set; }
        public string Nom { get; set; }
        public string BatimentEscalier { get; set; }
        public string Etage { get; set; }
        public TypeDeLot TypeDeLot { get; set; }
        public Nullable<double> Superficie { get; set; }
        public TypeDUsage Usage { get; set; }
    
        public virtual Immeuble Immeuble { get; set; }
        public virtual GroupeDeRepartition Proprietaires { get; set; }
        public virtual GroupeDeRepartition Occupants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentaire> Commentaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CleDeRepartition> ClesDeRepartition { get; set; }
    }
}
