//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodImmo.Models
{
    using System;
    
    public enum TypeDeDocument : long
    {
        ContratDeLocation = 0,
        ContratDeGestion = 1,
        ActeAchatVente = 2
    }
}
