//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodImmo.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class AdressePostale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdressePostale()
        {
            this.Pays = "France";
        }
    
        public long Id { get; set; }
        public string Rue { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
        public string Pays { get; set; }
        public string CodeAcces { get; set; }
        public string InfoAcces { get; set; }
        public string RueL2 { get; set; }
    
        public virtual CoordonneesDeContact CoordonneesDeContact { get; set; }
        public virtual Immeuble Immeuble { get; set; }
    }
}
