//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodImmo.Models
{
    using System;
    
    public enum TypeDeLot : int
    {
        Appartement = 0,
        Parking = 1,
        Cave = 2,
        Chambre = 3,
        Debarras = 4,
        Maison = 5,
        Immeuble = 6
    }
}
