//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodImmo.DataAccessLayer
{
    using System;
    using Microsoft.EntityFrameworkCore;
    using MethodImmo.Models;

    public class MethodImmoContext : DbContext
    {
        public MethodImmoContext(DbContextOptions<MethodImmoContext> options)
        : base(options)
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<AccesUtilisateur> AccesUtilisateurSet { get; set; }
        public virtual DbSet<MethodImmo.Models.Action> ActionSet { get; set; }
        public virtual DbSet<Commentaire> CommentaireSet { get; set; }
        public virtual DbSet<CompteBancaire> CompteBancaireSet { get; set; }
        public virtual DbSet<Contrat> ContratSet { get; set; }
        public virtual DbSet<CoordonneesBancaires> CoordonneesBancairesSet { get; set; }
        public virtual DbSet<Documentation> DocumentationSet { get; set; }
        public virtual DbSet<DroitsGroupeUtilisateurs> DroitsGroupeUtilisateursSet { get; set; }
        public virtual DbSet<GroupeDePersonnes> GroupeDePersonnesSet { get; set; }
        public virtual DbSet<Immeuble> ImmeubleSet { get; set; }
        public virtual DbSet<Personne> PersonneSet { get; set; }
        public virtual DbSet<CoordonneesDeContact> CoordonneesDeContactSet { get; set; }
        public virtual DbSet<AdressePostale> AdressePostaleSet { get; set; }
        public virtual DbSet<AdresseEmail> AdresseEmailSet { get; set; }
        public virtual DbSet<Telephone> TelephoneSet { get; set; }
        public virtual DbSet<VersionDeDocument> VersionDeDocumentSet { get; set; }
        public virtual DbSet<Lot> LotSet { get; set; }
        public virtual DbSet<Partenaire> PartenaireSet { get; set; }
        public virtual DbSet<CleDeRepartition> CleDeRepartitionSet { get; set; }
    }
}
